spring.application.name=repuestos-backend
server.port=3000

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/repuestos_db
spring.datasource.username=root
spring.datasource.password=arturo1302
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# n8n
n8n.ingesta-url=https://earache-removable-gulp.ngrok-free.dev/webhook/repuestos-sync
n8n.consulta-url=https://earache-removable-gulp.ngrok-free.dev/webhook/repuestos-buscar
